use super::*;

pub(in crate::ui::shell) struct AppViewSubscriptionsArgs {
    pub font_family_subscription: Subscription,
    pub font_fallbacks_subscription: Subscription,
    pub seed_color_subscription: Subscription,
    pub group_input_subscription: Subscription,
    pub group_select_subscription: Subscription,
    pub managed_key_select_subscription: Subscription,
    pub proxy_jump_select_subscription: Subscription,
    pub snippet_package_select_subscription: Subscription,
    pub language_select_subscription: Subscription,
    pub last_tab_close_behavior_select_subscription: Subscription,
    pub local_vault_auto_lock_duration_select_subscription: Subscription,
    pub monitor_history_select_subscription: Subscription,
    pub terminal_right_click_behavior_select_subscription: Subscription,
    pub sync_provider_select_subscription: Subscription,
    pub ai_provider_select_subscription: Subscription,
    pub ai_provider_kind_select_subscription: Subscription,
    pub web_search_kind_select_subscription: Subscription,
    pub keychain_filter_subscription: Subscription,
    pub filter_subscription: Subscription,
    pub trusted_filter_subscription: Subscription,
    pub forward_filter_subscription: Subscription,
    pub snippet_filter_subscription: Subscription,
    pub forward_profile_select_subscription: Subscription,
    pub local_sftp_path_subscription: Subscription,
    pub remote_sftp_path_subscription: Subscription,
    pub local_sftp_table_subscription: Subscription,
    pub remote_sftp_table_subscription: Subscription,
    pub rename_subscription: Subscription,
    pub sftp_prompt_subscription: Subscription,
    pub sftp_inline_rename_subscription: Subscription,
    pub search_subscription: Subscription,
    pub session_filter_subscription: Subscription,
    pub conversation_search_subscription: Subscription,
    pub session_snippets_filter_subscription: Subscription,
    pub session_agent_prompt_subscription: Subscription,
    pub session_agent_title_subscription: Subscription,
    pub terminal_focus_in_subscription: Subscription,
    pub terminal_focus_out_subscription: Subscription,
    pub window_activation_subscription: Subscription,
    pub keystroke_interceptor: Subscription,
}

impl AppView {
    pub(in crate::ui::shell) fn build_subscriptions(
        args: AppViewSubscriptionsArgs,
    ) -> AppViewSubscriptions {
        let AppViewSubscriptionsArgs {
            font_family_subscription,
            font_fallbacks_subscription,
            seed_color_subscription,
            group_input_subscription,
            group_select_subscription,
            managed_key_select_subscription,
            proxy_jump_select_subscription,
            snippet_package_select_subscription,
            language_select_subscription,
            last_tab_close_behavior_select_subscription,
            local_vault_auto_lock_duration_select_subscription,
            monitor_history_select_subscription,
            terminal_right_click_behavior_select_subscription,
            sync_provider_select_subscription,
            ai_provider_select_subscription,
            ai_provider_kind_select_subscription,
            web_search_kind_select_subscription,
            keychain_filter_subscription,
            filter_subscription,
            trusted_filter_subscription,
            forward_filter_subscription,
            snippet_filter_subscription,
            forward_profile_select_subscription,
            local_sftp_path_subscription,
            remote_sftp_path_subscription,
            local_sftp_table_subscription,
            remote_sftp_table_subscription,
            rename_subscription,
            sftp_prompt_subscription,
            sftp_inline_rename_subscription,
            search_subscription,
            session_filter_subscription,
            conversation_search_subscription,
            session_snippets_filter_subscription,
            session_agent_prompt_subscription,
            session_agent_title_subscription,
            terminal_focus_in_subscription,
            terminal_focus_out_subscription,
            window_activation_subscription,
            keystroke_interceptor,
        } = args;

        AppViewSubscriptions {
            _font_family_subscription: font_family_subscription,
            _font_fallbacks_subscription: font_fallbacks_subscription,
            _seed_color_subscription: seed_color_subscription,
            _group_input_subscription: group_input_subscription,
            _group_select_subscription: group_select_subscription,
            _managed_key_select_subscription: managed_key_select_subscription,
            _proxy_jump_select_subscription: proxy_jump_select_subscription,
            _snippet_package_select_subscription: snippet_package_select_subscription,
            _language_select_subscription: language_select_subscription,
            _last_tab_close_behavior_select_subscription:
                last_tab_close_behavior_select_subscription,
            _local_vault_auto_lock_duration_select_subscription:
                local_vault_auto_lock_duration_select_subscription,
            _monitor_history_select_subscription: monitor_history_select_subscription,
            _terminal_right_click_behavior_select_subscription:
                terminal_right_click_behavior_select_subscription,
            _sync_provider_select_subscription: sync_provider_select_subscription,
            _ai_provider_select_subscription: ai_provider_select_subscription,
            _ai_provider_kind_select_subscription: ai_provider_kind_select_subscription,
            _web_search_kind_select_subscription: web_search_kind_select_subscription,
            _keychain_filter_input_subscription: keychain_filter_subscription,
            _filter_input_subscription: filter_subscription,
            _trusted_filter_input_subscription: trusted_filter_subscription,
            _forward_filter_input_subscription: forward_filter_subscription,
            _snippet_filter_input_subscription: snippet_filter_subscription,
            _forward_profile_select_subscription: forward_profile_select_subscription,
            _local_sftp_path_input_subscription: local_sftp_path_subscription,
            _remote_sftp_path_input_subscription: remote_sftp_path_subscription,
            _local_sftp_table_subscription: local_sftp_table_subscription,
            _remote_sftp_table_subscription: remote_sftp_table_subscription,
            _rename_input_subscription: rename_subscription,
            _sftp_prompt_input_subscription: sftp_prompt_subscription,
            _sftp_inline_rename_input_subscription: sftp_inline_rename_subscription,
            _search_input_subscription: search_subscription,
            _session_filter_input_subscription: session_filter_subscription,
            _conversation_search_input_subscription: conversation_search_subscription,
            _session_snippets_filter_input_subscription: session_snippets_filter_subscription,
            _session_agent_prompt_input_subscription: session_agent_prompt_subscription,
            _session_agent_title_input_subscription: session_agent_title_subscription,
            _terminal_focus_in_subscription: terminal_focus_in_subscription,
            _terminal_focus_out_subscription: terminal_focus_out_subscription,
            _window_activation_subscription: window_activation_subscription,
            _terminal_keystroke_interceptor: keystroke_interceptor,
        }
    }
}
