use super::*;
use miaominal_core::profile::ImportSourceKind;
use miaominal_settings::AppLanguage;
use miaominal_sync::SyncProvider;

pub(in crate::ui::shell) struct HostEditorFormsArgs {
    pub name_input: Entity<InputState>,
    pub group_input: Entity<InputState>,
    pub group_select: Entity<SelectState<SearchableVec<String>>>,
    pub managed_key_select: Entity<SelectState<SearchableVec<ManagedKeySelectItem>>>,
    pub proxy_jump_select: Entity<SelectState<SearchableVec<ProxyJumpCandidateSelectItem>>>,
    pub charset_select: Entity<SelectState<SearchableVec<String>>>,
    pub creating_new_group: bool,
    pub tags_input: Entity<InputState>,
    pub host_input: Entity<InputState>,
    pub port_input: Entity<InputState>,
    pub username_input: Entity<InputState>,
    pub password_input: Entity<InputState>,
    pub private_key_input: Entity<InputState>,
    pub agent_identity_input: Entity<InputState>,
    pub certificate_input: Entity<InputState>,
    pub passphrase_input: Entity<InputState>,
    pub startup_command_input: Entity<InputState>,
    pub proxy_jump_profile_ids: Vec<String>,
    pub environment_variable_rows: Vec<HostEditorEnvironmentVariableRow>,
    pub editing_auth_method: AuthMethod,
    pub agent_forwarding_enabled: bool,
    pub shell_type: ShellType,
}

pub(in crate::ui::shell) struct WorkspaceFormsArgs {
    pub rename_input: Entity<InputState>,
    pub search_input: Entity<InputState>,
    pub agent_prompt_input: Entity<InputState>,
    pub session_snippets_filter_input: Entity<InputState>,
    pub local_path_input: Entity<InputState>,
    pub remote_path_input: Entity<InputState>,
    pub local_table: Entity<TableState<SftpBrowserTableDelegate>>,
    pub remote_table: Entity<TableState<SftpBrowserTableDelegate>>,
    pub prompt_input: Entity<InputState>,
    pub inline_rename_input: Entity<InputState>,
}

pub(in crate::ui::shell) struct PanelFormsArgs {
    pub filter_input: Entity<InputState>,
    pub trusted_filter_input: Entity<InputState>,
    pub keychain_filter_input: Entity<InputState>,
    pub managed_key_name_input: Entity<InputState>,
    pub managed_key_import_path_input: Entity<InputState>,
    pub managed_key_import_private_key_input: Entity<InputState>,
    pub managed_key_import_public_key_input: Entity<InputState>,
    pub managed_key_import_passphrase_input: Entity<InputState>,
    pub keychain_deploy_profile_select:
        Entity<SelectState<SearchableVec<ForwardProfileSelectItem>>>,
    pub keychain_deploy_location_input: Entity<InputState>,
    pub keychain_deploy_filename_input: Entity<InputState>,
    pub keychain_deploy_command_input: Entity<InputState>,
    pub forward_filter_input: Entity<InputState>,
    pub forward_profile_select: Entity<SelectState<SearchableVec<ForwardProfileSelectItem>>>,
    pub port_forward_label_input: Entity<InputState>,
    pub port_forward_listen_host_input: Entity<InputState>,
    pub port_forward_listen_port_input: Entity<InputState>,
    pub port_forward_target_host_input: Entity<InputState>,
    pub port_forward_target_port_input: Entity<InputState>,
    pub snippet_filter_input: Entity<InputState>,
    pub snippet_description_input: Entity<InputState>,
    pub snippet_package_input: Entity<InputState>,
    pub snippet_package_select: Entity<SelectState<SearchableVec<String>>>,
    pub creating_new_package: bool,
    pub snippet_script_input: Entity<InputState>,
    pub language_select: Entity<SelectState<Vec<SelectOption<AppLanguage>>>>,
    pub last_tab_close_behavior_select:
        Entity<SelectState<Vec<SelectOption<miaominal_settings::LastTabCloseBehavior>>>>,
    pub local_vault_auto_lock_duration_select:
        Entity<SelectState<Vec<SelectOption<miaominal_settings::LocalVaultAutoLockDuration>>>>,
    pub monitor_history_select:
        Entity<SelectState<Vec<SelectOption<miaominal_settings::MonitorHistoryDuration>>>>,
    pub terminal_right_click_behavior_select:
        Entity<SelectState<Vec<SelectOption<miaominal_settings::TerminalRightClickBehavior>>>>,
    pub profile_import_source_select: Entity<SelectState<Vec<SelectOption<ImportSourceKind>>>>,
    pub sync_provider_select: Entity<SelectState<Vec<SelectOption<SyncProvider>>>>,
    pub ai_provider_select: Entity<SelectState<Vec<SelectOption<String>>>>,
    pub ai_provider_kind_select:
        Entity<SelectState<Vec<SelectOption<miaominal_settings::AiProviderKind>>>>,
    pub web_search_kind_select:
        Entity<SelectState<Vec<SelectOption<miaominal_settings::WebSearchProviderKind>>>>,
    pub font_family_select: Entity<SelectState<SearchableVec<String>>>,
    pub font_fallbacks_input: Entity<InputState>,
    pub seed_color_picker: Entity<ColorPickerState>,
    pub key_capture_focus: FocusHandle,
    pub sync_github_token_input: Entity<InputState>,
    pub sync_github_gist_id_input: Entity<InputState>,
    pub sync_webdav_url_input: Entity<InputState>,
    pub sync_webdav_username_input: Entity<InputState>,
    pub sync_webdav_password_input: Entity<InputState>,
    pub sync_passphrase_input: Entity<InputState>,
    pub sync_passphrase_confirmation_input: Entity<InputState>,
    pub local_data_reset_confirmation_input: Entity<InputState>,
    pub local_vault_passphrase_input: Entity<InputState>,
    pub local_vault_passphrase_confirmation_input: Entity<InputState>,
    pub ai_provider_name_input: Entity<InputState>,
    pub ai_provider_model_input: Entity<InputState>,
    pub ai_provider_base_url_input: Entity<InputState>,
    pub ai_provider_api_key_input: Entity<InputState>,
    pub web_search_api_key_input: Entity<InputState>,
    pub web_search_endpoint_input: Entity<InputState>,
    pub web_search_max_results_input: Entity<InputState>,
}

impl AppView {
    pub(in crate::ui::shell) fn build_host_editor_forms(
        args: HostEditorFormsArgs,
    ) -> HostEditorForms {
        let HostEditorFormsArgs {
            name_input,
            group_input,
            group_select,
            managed_key_select,
            proxy_jump_select,
            charset_select,
            creating_new_group,
            tags_input,
            host_input,
            port_input,
            username_input,
            password_input,
            private_key_input,
            agent_identity_input,
            certificate_input,
            passphrase_input,
            startup_command_input,
            proxy_jump_profile_ids,
            environment_variable_rows,
            editing_auth_method,
            agent_forwarding_enabled,
            shell_type,
        } = args;

        HostEditorForms {
            name_input,
            group_input,
            group_select,
            managed_key_select,
            proxy_jump_select,
            charset_select,
            creating_new_group,
            tags_input,
            host_input,
            port_input,
            username_input,
            password_input,
            private_key_input,
            agent_identity_input,
            certificate_input,
            passphrase_input,
            startup_command_input,
            proxy_jump_profile_ids,
            selected_proxy_jump_hop: None,
            environment_variable_rows,
            shell_type,
            editing_auth_method,
            agent_forwarding_enabled,
        }
    }

    pub(in crate::ui::shell) fn build_workspace_forms(args: WorkspaceFormsArgs) -> WorkspaceForms {
        let WorkspaceFormsArgs {
            rename_input,
            search_input,
            agent_prompt_input,
            session_snippets_filter_input,
            local_path_input,
            remote_path_input,
            local_table,
            remote_table,
            prompt_input,
            inline_rename_input,
        } = args;

        WorkspaceForms {
            rename_input,
            search: TerminalSearchForms {
                input: search_input,
                open: false,
                visible: false,
                visibility: 0.0,
                animation: None,
                total: 0,
                current: None,
                status: None,
            },
            agent: WorkspaceAgentForms {
                prompt_input: agent_prompt_input,
            },
            snippets_panel: WorkspaceSnippetsForms {
                filter_input: session_snippets_filter_input,
                selected_package_filter: None,
            },
            sftp_browser: SftpBrowserForms {
                local_path_input,
                remote_path_input,
                local_path_editing: false,
                remote_path_editing: false,
                remote_path_submit_pending: false,
                local_table,
                remote_table,
                prompt_input,
                inline_rename_input,
            },
        }
    }

    pub(in crate::ui::shell) fn build_panel_forms(args: PanelFormsArgs) -> PanelForms {
        let PanelFormsArgs {
            filter_input,
            trusted_filter_input,
            keychain_filter_input,
            managed_key_name_input,
            managed_key_import_path_input,
            managed_key_import_private_key_input,
            managed_key_import_public_key_input,
            managed_key_import_passphrase_input,
            keychain_deploy_profile_select,
            keychain_deploy_location_input,
            keychain_deploy_filename_input,
            keychain_deploy_command_input,
            forward_filter_input,
            forward_profile_select,
            port_forward_label_input,
            port_forward_listen_host_input,
            port_forward_listen_port_input,
            port_forward_target_host_input,
            port_forward_target_port_input,
            snippet_filter_input,
            snippet_description_input,
            snippet_package_input,
            snippet_package_select,
            creating_new_package,
            snippet_script_input,
            language_select,
            last_tab_close_behavior_select,
            local_vault_auto_lock_duration_select,
            monitor_history_select,
            terminal_right_click_behavior_select,
            profile_import_source_select,
            sync_provider_select,
            ai_provider_select,
            ai_provider_kind_select,
            web_search_kind_select,
            font_family_select,
            font_fallbacks_input,
            seed_color_picker,
            key_capture_focus,
            sync_github_token_input,
            sync_github_gist_id_input,
            sync_webdav_url_input,
            sync_webdav_username_input,
            sync_webdav_password_input,
            sync_passphrase_input,
            sync_passphrase_confirmation_input,
            local_data_reset_confirmation_input,
            local_vault_passphrase_input,
            local_vault_passphrase_confirmation_input,
            ai_provider_name_input,
            ai_provider_model_input,
            ai_provider_base_url_input,
            ai_provider_api_key_input,
            web_search_api_key_input,
            web_search_endpoint_input,
            web_search_max_results_input,
        } = args;

        PanelForms {
            hosts: HostsForms { filter_input },
            trusted: TrustedHostsForms {
                filter_input: trusted_filter_input,
            },
            keychain: KeychainForms {
                filter_input: keychain_filter_input,
                name_input: managed_key_name_input,
                import_path_input: managed_key_import_path_input,
                import_private_key_input: managed_key_import_private_key_input,
                import_public_key_input: managed_key_import_public_key_input,
                import_passphrase_input: managed_key_import_passphrase_input,
                deploy_profile_select: keychain_deploy_profile_select,
                deploy_location_input: keychain_deploy_location_input,
                deploy_filename_input: keychain_deploy_filename_input,
                deploy_command_input: keychain_deploy_command_input,
            },
            forwarding: PortForwardingForms {
                filter_input: forward_filter_input,
                profile_select: forward_profile_select,
                label_input: port_forward_label_input,
                listen_host_input: port_forward_listen_host_input,
                listen_port_input: port_forward_listen_port_input,
                target_host_input: port_forward_target_host_input,
                target_port_input: port_forward_target_port_input,
            },
            snippets: SnippetsForms {
                filter_input: snippet_filter_input,
                description_input: snippet_description_input,
                package_input: snippet_package_input,
                package_select: snippet_package_select,
                creating_new_package,
                script_input: snippet_script_input,
            },
            settings: SettingsForms {
                language_select,
                last_tab_close_behavior_select,
                local_vault_auto_lock_duration_select,
                monitor_history_select,
                terminal_right_click_behavior_select,
                profile_import_source_select,
                sync_provider_select,
                ai_provider_select,
                ai_provider_kind_select,
                web_search_kind_select,
                font_family_select,
                font_fallbacks_input,
                seed_color_picker,
                key_capture_focus,
                recording_binding: None,
                pending_preview: None,
                pending_binding: None,
                sync_github_token_input,
                sync_github_gist_id_input,
                sync_webdav_url_input,
                sync_webdav_username_input,
                sync_webdav_password_input,
                sync_passphrase_input,
                sync_passphrase_confirmation_input,
                local_data_reset_confirmation_input,
                local_vault_passphrase_input,
                local_vault_passphrase_confirmation_input,
                ai_provider_name_input,
                ai_provider_model_input,
                ai_provider_base_url_input,
                ai_provider_api_key_input,
                web_search_api_key_input,
                web_search_endpoint_input,
                web_search_max_results_input,
                editing_ai_provider_id: None,
            },
        }
    }
}
