use super::*;
use crate::domain::profile::ImportSourceKind;
use crate::domain::sync::SyncProvider;
use crate::settings::AppLanguage;

impl AppView {
    pub(in crate::ui::shell) fn build_host_editor_forms(
        name_input: Entity<InputState>,
        group_input: Entity<InputState>,
        group_select: Entity<SelectState<SearchableVec<String>>>,
        managed_key_select: Entity<SelectState<SearchableVec<ManagedKeySelectItem>>>,
        proxy_jump_select: Entity<SelectState<SearchableVec<ProxyJumpCandidateSelectItem>>>,
        charset_select: Entity<SelectState<SearchableVec<String>>>,
        creating_new_group: bool,
        tags_input: Entity<InputState>,
        host_input: Entity<InputState>,
        port_input: Entity<InputState>,
        username_input: Entity<InputState>,
        password_input: Entity<InputState>,
        private_key_input: Entity<InputState>,
        agent_identity_input: Entity<InputState>,
        certificate_input: Entity<InputState>,
        passphrase_input: Entity<InputState>,
        startup_command_input: Entity<InputState>,
        proxy_jump_profile_ids: Vec<String>,
        environment_variable_rows: Vec<HostEditorEnvironmentVariableRow>,
        editing_auth_method: AuthMethod,
        agent_forwarding_enabled: bool,
        shell_type: ShellType,
    ) -> HostEditorForms {
        HostEditorForms {
            name_input,
            group_input,
            group_select,
            managed_key_select,
            proxy_jump_select,
            charset_select,
            creating_new_group,
            tags_input,
            host_input,
            port_input,
            username_input,
            password_input,
            private_key_input,
            agent_identity_input,
            certificate_input,
            passphrase_input,
            startup_command_input,
            proxy_jump_profile_ids,
            selected_proxy_jump_hop: None,
            environment_variable_rows,
            shell_type,
            editing_auth_method,
            agent_forwarding_enabled,
        }
    }

    pub(in crate::ui::shell) fn build_workspace_forms(
        rename_input: Entity<InputState>,
        search_input: Entity<InputState>,
        session_snippets_filter_input: Entity<InputState>,
        local_path_input: Entity<InputState>,
        remote_path_input: Entity<InputState>,
        local_table: Entity<TableState<SftpBrowserTableDelegate>>,
        remote_table: Entity<TableState<SftpBrowserTableDelegate>>,
        prompt_input: Entity<InputState>,
        inline_rename_input: Entity<InputState>,
    ) -> WorkspaceForms {
        WorkspaceForms {
            rename_input,
            search: TerminalSearchForms {
                input: search_input,
                open: false,
                visible: false,
                visibility: 0.0,
                animation: None,
                total: 0,
                current: None,
                status: None,
            },
            snippets_panel: WorkspaceSnippetsForms {
                filter_input: session_snippets_filter_input,
                selected_package_filter: None,
            },
            sftp_browser: SftpBrowserForms {
                local_path_input: local_path_input,
                remote_path_input,
                local_path_editing: false,
                remote_path_editing: false,
                remote_path_submit_pending: false,
                local_table,
                remote_table,
                prompt_input,
                inline_rename_input,
            },
        }
    }

    pub(in crate::ui::shell) fn build_panel_forms(
        filter_input: Entity<InputState>,
        keychain_filter_input: Entity<InputState>,
        managed_key_name_input: Entity<InputState>,
        managed_key_import_path_input: Entity<InputState>,
        managed_key_import_private_key_input: Entity<InputState>,
        managed_key_import_public_key_input: Entity<InputState>,
        managed_key_import_passphrase_input: Entity<InputState>,
        keychain_deploy_profile_select: Entity<
            SelectState<SearchableVec<ForwardProfileSelectItem>>,
        >,
        keychain_deploy_location_input: Entity<InputState>,
        keychain_deploy_filename_input: Entity<InputState>,
        keychain_deploy_command_input: Entity<InputState>,
        forward_filter_input: Entity<InputState>,
        forward_profile_select: Entity<SelectState<SearchableVec<ForwardProfileSelectItem>>>,
        port_forward_label_input: Entity<InputState>,
        port_forward_listen_host_input: Entity<InputState>,
        port_forward_listen_port_input: Entity<InputState>,
        port_forward_target_host_input: Entity<InputState>,
        port_forward_target_port_input: Entity<InputState>,
        snippet_filter_input: Entity<InputState>,
        snippet_description_input: Entity<InputState>,
        snippet_package_input: Entity<InputState>,
        snippet_package_select: Entity<SelectState<SearchableVec<String>>>,
        creating_new_package: bool,
        snippet_script_input: Entity<InputState>,
        language_select: Entity<SelectState<Vec<AppLanguage>>>,
        last_tab_close_behavior_select: Entity<SelectState<Vec<settings::LastTabCloseBehavior>>>,
        local_vault_auto_lock_duration_select: Entity<
            SelectState<Vec<settings::LocalVaultAutoLockDuration>>,
        >,
        monitor_history_select: Entity<SelectState<Vec<settings::MonitorHistoryDuration>>>,
        terminal_right_click_behavior_select: Entity<
            SelectState<Vec<settings::TerminalRightClickBehavior>>,
        >,
        profile_import_source_select: Entity<SelectState<Vec<ImportSourceKind>>>,
        sync_provider_select: Entity<SelectState<Vec<SyncProvider>>>,
        font_family_select: Entity<SelectState<SearchableVec<String>>>,
        font_fallbacks_input: Entity<InputState>,
        seed_color_picker: Entity<ColorPickerState>,
        key_capture_focus: FocusHandle,
        sync_github_token_input: Entity<InputState>,
        sync_github_gist_id_input: Entity<InputState>,
        sync_webdav_url_input: Entity<InputState>,
        sync_webdav_username_input: Entity<InputState>,
        sync_webdav_password_input: Entity<InputState>,
        sync_passphrase_input: Entity<InputState>,
        sync_passphrase_confirmation_input: Entity<InputState>,
        local_data_reset_confirmation_input: Entity<InputState>,
        local_vault_passphrase_input: Entity<InputState>,
        local_vault_passphrase_confirmation_input: Entity<InputState>,
    ) -> PanelForms {
        PanelForms {
            hosts: HostsForms { filter_input },
            keychain: KeychainForms {
                filter_input: keychain_filter_input,
                name_input: managed_key_name_input,
                import_path_input: managed_key_import_path_input,
                import_private_key_input: managed_key_import_private_key_input,
                import_public_key_input: managed_key_import_public_key_input,
                import_passphrase_input: managed_key_import_passphrase_input,
                deploy_profile_select: keychain_deploy_profile_select,
                deploy_location_input: keychain_deploy_location_input,
                deploy_filename_input: keychain_deploy_filename_input,
                deploy_command_input: keychain_deploy_command_input,
            },
            forwarding: PortForwardingForms {
                filter_input: forward_filter_input,
                profile_select: forward_profile_select,
                label_input: port_forward_label_input,
                listen_host_input: port_forward_listen_host_input,
                listen_port_input: port_forward_listen_port_input,
                target_host_input: port_forward_target_host_input,
                target_port_input: port_forward_target_port_input,
            },
            snippets: SnippetsForms {
                filter_input: snippet_filter_input,
                description_input: snippet_description_input,
                package_input: snippet_package_input,
                package_select: snippet_package_select,
                creating_new_package,
                script_input: snippet_script_input,
            },
            settings: SettingsForms {
                language_select,
                last_tab_close_behavior_select,
                local_vault_auto_lock_duration_select,
                monitor_history_select,
                terminal_right_click_behavior_select,
                profile_import_source_select,
                sync_provider_select,
                font_family_select,
                font_fallbacks_input,
                seed_color_picker,
                key_capture_focus,
                recording_binding: None,
                pending_preview: None,
                pending_binding: None,
                sync_github_token_input,
                sync_github_gist_id_input,
                sync_webdav_url_input,
                sync_webdav_username_input,
                sync_webdav_password_input,
                sync_passphrase_input,
                sync_passphrase_confirmation_input,
                local_data_reset_confirmation_input,
                local_vault_passphrase_input,
                local_vault_passphrase_confirmation_input,
            },
        }
    }
}
