use super::*;

impl AppView {
    pub(in crate::ui::shell) fn build_subscriptions(
        font_family_subscription: Subscription,
        font_fallbacks_subscription: Subscription,
        seed_color_subscription: Subscription,
        group_input_subscription: Subscription,
        group_select_subscription: Subscription,
        managed_key_select_subscription: Subscription,
        proxy_jump_select_subscription: Subscription,
        snippet_package_select_subscription: Subscription,
        language_select_subscription: Subscription,
        last_tab_close_behavior_select_subscription: Subscription,
        local_vault_auto_lock_duration_select_subscription: Subscription,
        monitor_history_select_subscription: Subscription,
        terminal_right_click_behavior_select_subscription: Subscription,
        sync_provider_select_subscription: Subscription,
        keychain_filter_subscription: Subscription,
        filter_subscription: Subscription,
        forward_filter_subscription: Subscription,
        snippet_filter_subscription: Subscription,
        forward_profile_select_subscription: Subscription,
        local_sftp_path_subscription: Subscription,
        remote_sftp_path_subscription: Subscription,
        local_sftp_table_subscription: Subscription,
        remote_sftp_table_subscription: Subscription,
        rename_subscription: Subscription,
        sftp_prompt_subscription: Subscription,
        sftp_inline_rename_subscription: Subscription,
        search_subscription: Subscription,
        session_snippets_filter_subscription: Subscription,
        terminal_focus_in_subscription: Subscription,
        terminal_focus_out_subscription: Subscription,
        window_activation_subscription: Subscription,
        keystroke_interceptor: Subscription,
    ) -> AppViewSubscriptions {
        AppViewSubscriptions {
            _font_family_subscription: font_family_subscription,
            _font_fallbacks_subscription: font_fallbacks_subscription,
            _seed_color_subscription: seed_color_subscription,
            _group_input_subscription: group_input_subscription,
            _group_select_subscription: group_select_subscription,
            _managed_key_select_subscription: managed_key_select_subscription,
            _proxy_jump_select_subscription: proxy_jump_select_subscription,
            _snippet_package_select_subscription: snippet_package_select_subscription,
            _language_select_subscription: language_select_subscription,
            _last_tab_close_behavior_select_subscription:
                last_tab_close_behavior_select_subscription,
            _local_vault_auto_lock_duration_select_subscription:
                local_vault_auto_lock_duration_select_subscription,
            _monitor_history_select_subscription: monitor_history_select_subscription,
            _terminal_right_click_behavior_select_subscription:
                terminal_right_click_behavior_select_subscription,
            _sync_provider_select_subscription: sync_provider_select_subscription,
            _keychain_filter_input_subscription: keychain_filter_subscription,
            _filter_input_subscription: filter_subscription,
            _forward_filter_input_subscription: forward_filter_subscription,
            _snippet_filter_input_subscription: snippet_filter_subscription,
            _forward_profile_select_subscription: forward_profile_select_subscription,
            _local_sftp_path_input_subscription: local_sftp_path_subscription,
            _remote_sftp_path_input_subscription: remote_sftp_path_subscription,
            _local_sftp_table_subscription: local_sftp_table_subscription,
            _remote_sftp_table_subscription: remote_sftp_table_subscription,
            _rename_input_subscription: rename_subscription,
            _sftp_prompt_input_subscription: sftp_prompt_subscription,
            _sftp_inline_rename_input_subscription: sftp_inline_rename_subscription,
            _search_input_subscription: search_subscription,
            _session_snippets_filter_input_subscription: session_snippets_filter_subscription,
            _terminal_focus_in_subscription: terminal_focus_in_subscription,
            _terminal_focus_out_subscription: terminal_focus_out_subscription,
            _window_activation_subscription: window_activation_subscription,
            _terminal_keystroke_interceptor: keystroke_interceptor,
        }
    }
}
