[package]
name = "miaominal-settings"
version.workspace = true
edition.workspace = true
publish = false

[features]
default = []
desktop-ui = ["dep:fontdb", "dep:gpui-kit"]

[dependencies]
fontdb = { workspace = true, optional = true }
gpui-kit = { workspace = true, optional = true, features = ["component"] }
material-colors.workspace = true
miaominal-core = { path = "../miaominal-core" }
serde.workspace = true
serde_json.workspace = true
sys-locale.workspace = true
toml.workspace = true
uuid.workspace = true
